Add arm64 support for Monero
btcpayserver/dockerfile-deps pull request #38
Opened 2022-01-15 12:53 UTC by ksdhans

This adds arm64 support for Monero. It's currently syncing on my Raspberry Pi 4 (haven't tried setting up a wallet yet, as per the extended setup instructions).

Addresses: https://github.com/btcpayserver/btcpayserver-docker/issues/571

2022-01-17 10:01 UTC, Kukks requested changes
The image is for 17.3.0 but you have it in the 17.2.3 directory

2022-01-17 11:56 UTC, ksdhans commented
Oops! I just took the latest download and didn't pay attention to the version. I'll downgrade it to 17.2.3 to remain inline with the latest used on other platforms.

2022-01-17 12:29 UTC, merged

2022-01-17 12:48 UTC, Kukks commented
It seems like your dockerfile did not work and the CI failed https://app.circleci.com/pipelines/github/btcpayserver/dockerfile-deps/503/workflows/c1972461-f40b-43ca-9775-6fd5ca4ad051/jobs/850

2022-01-17 13:24 UTC, ksdhans commented
Strange. It worked for me when I built it on my Windows machine. The line where it's failing is identical to the one in linuxamd64.Dockerfile. Surely that line would work on any Debian system regardless of CPU architecture?

I'm not sure what to do about this, either:
[Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested

I'm new to Docker, so maybe someone with more experience could take a look?

2022-01-18 01:12 UTC, ksdhans commented
The most common suggestion for that warning appears to be adding "--platform linux/arm64/v8" to the docker build command line.